server:
  port: 9080

spring:
  application:
    name: token-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"